export default {
  neutral: {
    value: 'hsl(200, 25%, 40%)',
    darkness: 60,
    darkHueAngle: 0,
    darkSaturation: 0,
    lightness: 95,
    lightHueAngle: 5,
    lightSaturation: 1,
    hueEasing: 'easeInOutSine',
    saturationEasing: 'easeInOutSine',
    lightnessEasing: 'easeInOutSine',
    darknessEasing: 'easeInOutSine',
  },
  cyan: {
    value: 'hsl(192, 75%, 55%)',
    darkness: 65,
    darkHueAngle: -18,
    darkSaturation: 8,
    lightness: 95,
    lightHueAngle: 0,
    lightSaturation: 0,
    hueEasing: 'easeInOutSine',
    saturationEasing: 'easeInOutSine',
    lightnessEasing: 'easeInOutSine',
    darknessEasing: 'easeInOutSine',
  },
  blue: {
    value: 'hsl(215, 65%, 45%)',
    darkness: 68,
    darkHueAngle: -8,
    darkSaturation: 40,
    lightness: 95,
    lightHueAngle: 0,
    lightSaturation: 40,
    hueEasing: 'easeInOutSine',
    saturationEasing: 'easeInOutSine',
    lightnessEasing: 'easeInOutSine',
    darknessEasing: 'easeInOutSine',
  },
  green: {
    value: 'hsl(160, 90%, 25%)',
    darkness: 65,
    darkHueAngle: -10,
    darkSaturation: 0,
    lightness: 95,
    lightHueAngle: 0,
    lightSaturation: 150,
    hueEasing: 'easeInOutSine',
    saturationEasing: 'easeInOutSine',
    lightnessEasing: 'easeInOutSine',
    darknessEasing: 'easeInOutSine',
  },
  yellow: {
    value: 'hsl(40, 100%, 55%)',
    darkness: 45,
    darkHueAngle: 20,
    darkSaturation: 120,
    lightness: 95,
    lightHueAngle: -5,
    lightSaturation: 100,
    hueEasing: 'easeOutQuart',
    saturationEasing: 'easeInOutSine',
    lightnessEasing: 'easeInOutSine',
    darknessEasing: 'easeInOutSine',
  },
  red: {
    value: 'hsl(350, 90%, 45%)',
    darkness: 65,
    darkHueAngle: 15,
    darkSaturation: 40,
    lightness: 95,
    lightHueAngle: 0,
    lightSaturation: 20,
    hueEasing: 'easeInOutSine',
    saturationEasing: 'easeInOutSine',
    lightnessEasing: 'easeOutQuad',
    darknessEasing: 'easeInOutSine',
  },
  magenta: {
    value: 'hsl(330, 90%, 40%)',
    darkness: 65,
    darkHueAngle: 0,
    darkSaturation: 0,
    lightness: 95,
    lightHueAngle: 0,
    lightSaturation: 0,
    hueEasing: 'easeInOutSine',
    saturationEasing: 'easeInOutSine',
    lightnessEasing: 'easeInOutSine',
    darknessEasing: 'easeInOutSine',
  },
};
